# Generated by Django 3.1.4 on 2021-01-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0006_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='name',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='price',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='quantity',
        ),
        migrations.AddField(
            model_name='extras',
            name='requests',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
