# Generated by Django 3.1.4 on 2021-01-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0007_auto_20210105_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='requests',
        ),
        migrations.AddField(
            model_name='extras',
            name='extras',
            field=models.TextField(default='', max_length=300),
        ),
    ]
